# Generated by Django 3.0.7 on 2020-06-15 12:19

from django.db import migrations, models
import django.db.models.deletion
import inventory.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.AlterField(
            model_name='images',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.ImageField(upload_to=inventory.models.UploadToPathAndRename('images/')),
        ),
        migrations.AlterField(
            model_name='images',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.StoredObjects', validators=[inventory.models.restrict_total_image]),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='category',
            field=models.IntegerField(blank=True, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='locationEntityUUID',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[inventory.models.validate_uuid], verbose_name='Location Entity UUID'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='nestable',
            field=models.BooleanField(default=False, verbose_name='Nestable'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='owningEntity',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[inventory.models.validate_uuid], verbose_name='Owning Entity'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='standarisedObject',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[inventory.models.validate_uuid], verbose_name='Standarised Object'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='visibility',
            field=models.IntegerField(blank=True, null=True, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='inventory.Types', verbose_name='Type'),
        ),
    ]
