# Generated by Django 3.0.7 on 2020-06-15 12:26

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200615_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedobjects',
            name='locationEntityUUID',
            field=models.CharField(blank=True, max_length=36, null=True, validators=[inventory.models.validate_uuid], verbose_name='Location Entity UUID'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='owningEntity',
            field=models.CharField(blank=True, max_length=36, null=True, validators=[inventory.models.validate_uuid], verbose_name='Owning Entity'),
        ),
        migrations.AlterField(
            model_name='storedobjects',
            name='standarisedObject',
            field=models.CharField(blank=True, max_length=36, null=True, validators=[inventory.models.validate_uuid], verbose_name='Standarised Object'),
        ),
    ]
