# Generated by Django 3.0.7 on 2020-07-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200615_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestableObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containingUUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containingObject', to='inventory.StoredObjects', unique=True)),
                ('holdingUUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdingObject', to='inventory.StoredObjects')),
            ],
            options={
                'verbose_name_plural': 'Nestable Objects',
                'unique_together': {('holdingUUID', 'containingUUID')},
            },
        ),
    ]
